### ISSUE TITLE
install problem in ubuntu 14.04.1:  ImportError: No module named 'utils.mainwin'

### ISSUE THREAD

**Issue by rhoconlinux** [karim88/PlankSetting#1]
Just finished a fresh install of ubuntu 14.04.1. 

The install script exits without reporting any issue, however the program doesn't starts. The output is

<pre>rho@zeenbook:~$ planksetting 
** (Main.py:27939): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/share/planksetting/Main.py", line 4, in <module>
    from utils.mainwin import Mainwin
ImportError: No module named 'utils.mainwin'
 </pre> 

Any clues on how to solve it? 
Previous versions didn't made this error. 
Thanks!

**Comment by ouladck** [comment]
Thank you for reporting the bug,
the problem are caused by some change in access permission in utils and po directory, and that make interpretor don't find utils.mainwin, you can fix that by typing that in terminal:

> sudo chmod 775 /usr/share/planksetting/*

Sorry for the problem.

**Comment by rhoconlinux** [comment]
thanks! :dancers:
