### ISSUE TITLE
Not launched in opensuse leap

### ISSUE THREAD

**Issue by lafaurie** [karim88/PlankSetting#3]
I have these errors when I tried to execute the application

planksetting 

(Main.py:19436): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(Main.py:19436): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(Main.py:19436): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
/usr/share/planksetting/Main.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "/usr/share/planksetting/Main.py", line 4, in <module>
    from utils.mainwin import Mainwin
ImportError: No module named 'utils.mainwin'

**Comment by ouladck** [comment]
Thank you for reporting this bug,
and sorry for the later reply, I fixed this bug in v1.4
https://github.com/karim88/PlankSetting/archive/v1.4.zip

Have a nice day
